import { FormEvent, useEffect, useState } from "react";
import { Link, useLocation } from "wouter";
import { Heart, LogOut, MapPin, Package, Plus, Trash2, User } from "lucide-react";
import { getGetMyOrdersQueryKey, getListCustomerAddressesQueryKey, getListFavoritesQueryKey, useAddCustomerAddress, useDeleteCustomerAddress, useGetMyOrders, useListCustomerAddresses, useListFavorites, useListGovernorates, useUpdateCustomerProfile } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ProductCard } from "@/components/storefront/ProductCard";
import { orderStatusLabels } from "@/components/storefront/OrderTimeline";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/hooks/use-toast";

export default function Account() {
  const [, setLocation] = useLocation();
  const { customer, setCustomer, isCustomerAuthLoaded, logoutCustomer } = useAuth();
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [activeTab, setActiveTab] = useState(new URLSearchParams(window.location.search).get("tab") || "orders");
  const orderParams = { page: 1, limit: 20 };
  const orders = useGetMyOrders(orderParams, { query: { queryKey: getGetMyOrdersQueryKey(orderParams), enabled: Boolean(customer), retry: false } });
  const favorites = useListFavorites({ query: { queryKey: getListFavoritesQueryKey(), enabled: Boolean(customer), retry: false } });
  const addresses = useListCustomerAddresses({ query: { queryKey: getListCustomerAddressesQueryKey(), enabled: Boolean(customer), retry: false } });
  const { data: governorates } = useListGovernorates();
  const [profile, setProfile] = useState({ name: "", email: "", mobile: "" });
  const [addressOpen, setAddressOpen] = useState(false);
  const [address, setAddress] = useState({ governorateId: 0, city: "", detailedAddress: "", landmark: "", isDefault: false });
  useEffect(() => { if (isCustomerAuthLoaded && !customer) setLocation("/login?next=/account"); }, [isCustomerAuthLoaded, customer, setLocation]);
  useEffect(() => { if (customer) setProfile({ name: customer.name, email: customer.email || "", mobile: customer.mobile }); }, [customer]);
  const updateProfile = useUpdateCustomerProfile({ mutation: { onSuccess: updated => { setCustomer(updated); toast({ title: "تم حفظ بياناتك" }); }, onError: () => toast({ title: "تعذر حفظ البيانات", variant: "destructive" }) } });
  const refreshAddresses = () => queryClient.invalidateQueries({ queryKey: getListCustomerAddressesQueryKey() });
  const addAddress = useAddCustomerAddress({ mutation: { onSuccess: () => { refreshAddresses(); setAddressOpen(false); setAddress({ governorateId: 0, city: "", detailedAddress: "", landmark: "", isDefault: false }); toast({ title: "تم حفظ العنوان" }); }, onError: () => toast({ title: "تعذر حفظ العنوان", variant: "destructive" }) } });
  const deleteAddress = useDeleteCustomerAddress({ mutation: { onSuccess: refreshAddresses } });
  if (!customer) return <div className="container mx-auto px-4 py-20 text-center">جاري فتح حسابك...</div>;
  const submitAddress = (event: FormEvent) => { event.preventDefault(); addAddress.mutate({ data: address }); };
  const submitProfile = (event: FormEvent) => { event.preventDefault(); updateProfile.mutate({ data: { name: profile.name, email: profile.email || undefined, mobile: profile.mobile } }); };

  return <div className="container mx-auto max-w-6xl px-4 py-9"><div className="grid gap-7 md:grid-cols-[240px_1fr]"><aside><Card className="rounded-2xl text-center"><CardContent className="p-6"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-primary text-2xl font-black text-white">{customer.name.charAt(0)}</div><h1 className="mt-4 text-xl font-black">{customer.name}</h1><p className="mt-1 text-sm text-muted-foreground" dir="ltr">{customer.mobile}</p></CardContent></Card><Button variant="outline" className="mt-3 w-full text-destructive" onClick={async () => { await logoutCustomer(); setLocation("/login"); }}><LogOut className="ml-2 h-4 w-4" /> تسجيل الخروج</Button></aside>
    <main className="min-w-0"><Tabs value={activeTab} onValueChange={value => { setActiveTab(value); window.history.replaceState(null, "", `/account?tab=${value}`); }}><TabsList className="mb-6 h-auto w-full justify-start overflow-x-auto rounded-xl p-1"><TabsTrigger value="orders" className="gap-2 py-2.5"><Package className="h-4 w-4" /> طلباتي</TabsTrigger><TabsTrigger value="favorites" className="gap-2 py-2.5"><Heart className="h-4 w-4" /> المفضلة</TabsTrigger><TabsTrigger value="addresses" className="gap-2 py-2.5"><MapPin className="h-4 w-4" /> عناويني</TabsTrigger><TabsTrigger value="profile" className="gap-2 py-2.5"><User className="h-4 w-4" /> بياناتي</TabsTrigger></TabsList>
      <TabsContent value="orders"><h2 className="mb-5 text-2xl font-black">طلباتك السابقة</h2>{orders.isLoading ? <div className="space-y-4">{[1, 2, 3].map(value => <Skeleton key={value} className="h-36 rounded-2xl" />)}</div> : !orders.data?.items.length ? <Empty icon={Package} text="لم تنشئ أي طلب بعد" action="تصفح الكتب" href="/catalog" /> : <div className="space-y-4">{orders.data.items.map(order => <Card key={order.id} className="overflow-hidden rounded-2xl"><CardHeader className="border-b bg-slate-50"><div className="flex flex-wrap items-center justify-between gap-4"><div><span className="text-xs text-muted-foreground">رقم الطلب</span><CardTitle className="text-base" dir="ltr">{order.orderNumber}</CardTitle></div><div><span className="text-xs text-muted-foreground">التاريخ</span><strong className="block text-sm">{new Date(order.createdAt).toLocaleDateString("ar-EG")}</strong></div><strong>{order.total} ج.م</strong><Badge variant="secondary">{orderStatusLabels[order.status] || order.status}</Badge><Button size="sm" variant="outline" asChild><Link href={`/orders/${order.id}`}>التفاصيل</Link></Button></div></CardHeader><CardContent className="flex gap-3 overflow-x-auto p-4">{order.items.map(item => <div key={`${order.id}-${item.productId}`} className="flex min-w-52 gap-3 rounded-xl border p-2"><div className="h-14 w-10 overflow-hidden rounded bg-muted">{item.coverImage ? <img src={item.coverImage} alt={item.nameAr} className="h-full w-full object-cover" /> : null}</div><div className="min-w-0"><strong className="line-clamp-1 text-sm">{item.nameAr}</strong><span className="text-xs text-muted-foreground">الكمية: {item.quantity}</span></div></div>)}</CardContent></Card>)}</div>}</TabsContent>
      <TabsContent value="favorites"><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl font-black">منتجاتك المفضلة</h2><span className="text-sm text-muted-foreground">{favorites.data?.length || 0} منتج</span></div>{favorites.isLoading ? <div className="grid grid-cols-2 gap-4 lg:grid-cols-3">{[1, 2, 3].map(value => <Skeleton key={value} className="h-96 rounded-2xl" />)}</div> : !favorites.data?.length ? <Empty icon={Heart} text="لم تضف منتجات للمفضلة" action="اكتشف الكتب" href="/catalog" /> : <div className="grid grid-cols-2 gap-4 lg:grid-cols-3">{favorites.data.map(product => <ProductCard key={product.id} product={product} isFavorite />)}</div>}</TabsContent>
      <TabsContent value="addresses"><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl font-black">عناوين التوصيل</h2><Dialog open={addressOpen} onOpenChange={setAddressOpen}><DialogTrigger asChild><Button size="sm"><Plus className="ml-2 h-4 w-4" /> إضافة عنوان</Button></DialogTrigger><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>عنوان جديد</DialogTitle></DialogHeader><form onSubmit={submitAddress} className="space-y-4"><div><Label className="mb-2 block">المحافظة</Label><Select value={address.governorateId ? String(address.governorateId) : ""} onValueChange={value => setAddress(current => ({ ...current, governorateId: Number(value) }))}><SelectTrigger><SelectValue placeholder="اختر المحافظة" /></SelectTrigger><SelectContent>{governorates?.filter(item => item.isActive).map(item => <SelectItem key={item.id} value={String(item.id)}>{item.nameAr}</SelectItem>)}</SelectContent></Select></div><div><Label className="mb-2 block">المدينة / الحي</Label><Input required value={address.city} onChange={event => setAddress(current => ({ ...current, city: event.target.value }))} /></div><div><Label className="mb-2 block">العنوان بالتفصيل</Label><Input required value={address.detailedAddress} onChange={event => setAddress(current => ({ ...current, detailedAddress: event.target.value }))} /></div><div><Label className="mb-2 block">علامة مميزة</Label><Input value={address.landmark} onChange={event => setAddress(current => ({ ...current, landmark: event.target.value }))} /></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={address.isDefault} onChange={event => setAddress(current => ({ ...current, isDefault: event.target.checked }))} /> اجعله العنوان الافتراضي</label><Button type="submit" className="w-full" disabled={!address.governorateId || addAddress.isPending}>حفظ العنوان</Button></form></DialogContent></Dialog></div>{addresses.isLoading ? <Skeleton className="h-40 rounded-2xl" /> : !addresses.data?.length ? <Empty icon={MapPin} text="لم تحفظ عناوين بعد" /> : <div className="grid gap-4 sm:grid-cols-2">{addresses.data.map(item => <Card key={item.id} className="rounded-2xl"><CardContent className="p-5"><div className="flex justify-between"><MapPin className="h-6 w-6 text-secondary" />{item.isDefault && <Badge>الافتراضي</Badge>}</div><strong className="mt-4 block">{item.governorate} - {item.city}</strong><p className="mt-1 text-sm text-muted-foreground">{item.detailedAddress}{item.landmark && `، ${item.landmark}`}</p><Button variant="ghost" size="sm" className="mt-4 text-destructive" onClick={() => deleteAddress.mutate({ id: item.id })}><Trash2 className="ml-1 h-4 w-4" /> حذف</Button></CardContent></Card>)}</div>}</TabsContent>
      <TabsContent value="profile"><h2 className="mb-5 text-2xl font-black">بيانات الحساب</h2><Card className="max-w-xl rounded-2xl"><CardContent className="p-6"><form onSubmit={submitProfile} className="space-y-4">{[["الاسم", "name"], ["البريد الإلكتروني", "email"], ["رقم الموبايل", "mobile"]].map(([label, key]) => <div key={key}><Label className="mb-2 block">{label}</Label><Input value={profile[key as keyof typeof profile]} onChange={event => setProfile(current => ({ ...current, [key]: event.target.value }))} dir={key === "mobile" || key === "email" ? "ltr" : "rtl"} required={key !== "email"} /></div>)}<Button type="submit" disabled={updateProfile.isPending}>حفظ التعديلات</Button></form></CardContent></Card></TabsContent>
    </Tabs></main></div></div>;
}
function Empty({ icon: Icon, text, action, href }: { icon: typeof Package; text: string; action?: string; href?: string }) { return <div className="rounded-2xl border border-dashed bg-muted/20 py-16 text-center"><Icon className="mx-auto mb-3 h-12 w-12 text-muted-foreground/30" /><p className="text-muted-foreground">{text}</p>{action && href && <Button className="mt-4" variant="outline" asChild><Link href={href}>{action}</Link></Button>}</div>; }
