import { Mail, MapPin, Phone } from "lucide-react";
import { getListFaqsQueryKey, useGetSiteSettings, useListFaqs } from "@workspace/api-client-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Card, CardContent } from "@/components/ui/card";
import { Seo } from "@/components/storefront/Seo";

const pages: Record<string, { title: string; intro: string; sections: [string, string][] }> = {
  "/about": { title: "من نحن", intro: "مكتبة دوت كوم متجر متخصص في الكتب التعليمية والمراجعات للطلاب في مصر.", sections: [["مهمتنا", "تسهيل الوصول إلى الكتاب المناسب بسعر ومخزون واضحين، وربط واجهة المتجر مباشرة بإدارة المكتبة."], ["طريقة العمل", "تُدار المنتجات والأسعار والمخزون يدويًا من لوحة الإدارة، ويعمل الموقع بشكل مستقل حاليًا تمهيدًا لأي تكامل مستقبلي."]] },
  "/shipping-policy": { title: "سياسة الشحن", intro: "تُحسب تكلفة الشحن آليًا حسب المحافظة والمدينة ومحتويات السلة.", sections: [["التكلفة", "تظهر تكلفة الأساس وإضافة المدينة وأي خصم شحن قبل تأكيد الطلب، ويُحفظ Snapshot التسعير مع الطلب."], ["الشحن المجاني", "يُطبق عند استيفاء قواعد المنتج أو الكوبون أو حد المحافظة. السلة المختلطة لا تصبح مجانية إلا إذا تحققت قاعدة كاملة."], ["مدة التوصيل", "المدة المعروضة تقديرية حسب إعدادات المحافظة، ويؤكد فريق خدمة العملاء تفاصيل التسليم."]] },
  "/return-policy": { title: "الإلغاء والاسترجاع", intro: "لا يستطيع العميل إلغاء الطلب المرسل مباشرة.", sections: [["طلب الإلغاء", "يمكن إرسال طلب إلغاء من صفحة تفاصيل الطلب قبل مراحل الشحن المتقدمة. يراجع موظف مخوّل الطلب ويوافق عليه أو يرفضه."], ["الاسترجاع", "تُراجع حالات الاسترجاع مع خدمة العملاء وفق حالة الكتب والتغليف ومرحلة الطلب. لا تُنفذ تغييرات المخزون إلا من خلال الإجراءات الإدارية المسجلة."]] },
  "/privacy": { title: "سياسة الخصوصية", intro: "نستخدم بياناتك فقط لتقديم الحساب والطلب والتوصيل وخدمة العملاء.", sections: [["البيانات", "قد نحفظ الاسم والهاتف والبريد وعناوين التوصيل وتاريخ الطلبات والمفضلة."], ["الحماية", "تُخزن كلمات المرور بصورة مشفرة، وتُقيد صلاحيات الموظفين، وتُسجل الإجراءات المهمة لأغراض المراجعة."], ["المشاركة", "لا نبيع بيانات العملاء. قد تُشارك بيانات التوصيل الضرورية مع شركة الشحن عند بدء التشغيل الفعلي."]] },
  "/terms": { title: "الشروط والأحكام", intro: "باستخدام المتجر وإرسال الطلب أنت توافق على الشروط التالية.", sections: [["الأسعار والتوفر", "تُعرض الأسعار والمخزون من قاعدة البيانات، لكن يبقى الطلب خاضعًا للتحقق النهائي قبل التجهيز."], ["الدفع", "الدفع نقدًا عند الاستلام هو الوسيلة المفعلة حاليًا. فوري غير مفعل ولا يدّعي الموقع خلاف ذلك."], ["الفاتورة", "تصدر فاتورة بسيطة غير ضريبية باسم مكتبة دوت كوم."]] },
};

export default function InformationPage() {
  const path = window.location.pathname;
  const { data: settings } = useGetSiteSettings();
  const { data: faqs } = useListFaqs({ query: { queryKey: getListFaqsQueryKey(), enabled: path === "/faq" } });
  if (path === "/contact") return <Shell title="تواصل معنا" intro="يسعدنا الرد على استفسارات المنتجات والطلبات."><div className="grid gap-4 sm:grid-cols-3">{settings?.phoneNumber && <Contact icon={Phone} label="الهاتف" value={settings.phoneNumber} href={`tel:${settings.phoneNumber}`} />}{settings?.email && <Contact icon={Mail} label="البريد" value={settings.email} href={`mailto:${settings.email}`} />}{settings?.address && <Contact icon={MapPin} label="العنوان" value={settings.address} />}</div></Shell>;
  if (path === "/faq") return <Shell title="الأسئلة الشائعة" intro="إجابات تديرها المكتبة من لوحة التحكم.">{faqs?.length ? <Accordion type="single" collapsible className="rounded-2xl border bg-white px-5">{faqs.map(item => <AccordionItem key={item.id} value={String(item.id)}><AccordionTrigger className="text-right font-bold">{item.questionAr}</AccordionTrigger><AccordionContent className="leading-7 text-muted-foreground">{item.answerAr}</AccordionContent></AccordionItem>)}</Accordion> : <div className="rounded-2xl border border-dashed py-14 text-center text-muted-foreground">لا توجد أسئلة منشورة حاليًا.</div>}</Shell>;
  const page = pages[path] || pages["/about"];
  return <Shell title={page.title} intro={page.intro}><div className="space-y-4">{page.sections.map(([title, text]) => <Card key={title} className="rounded-2xl"><CardContent className="p-6"><h2 className="text-xl font-black">{title}</h2><p className="mt-3 leading-8 text-muted-foreground">{text}</p></CardContent></Card>)}</div></Shell>;
}
function Shell({ title, intro, children }: { title: string; intro: string; children: React.ReactNode }) { return <div className="container mx-auto max-w-4xl px-4 py-12"><Seo title={`${title} | مكتبة دوت كوم`} description={intro} /><div className="mb-9"><h1 className="text-4xl font-black">{title}</h1><p className="mt-3 max-w-2xl text-lg leading-8 text-muted-foreground">{intro}</p></div>{children}</div>; }
function Contact({ icon: Icon, label, value, href }: { icon: typeof Phone; label: string; value: string; href?: string }) { const content = <><Icon className="mx-auto h-7 w-7 text-secondary" /><strong className="mt-3 block">{label}</strong><span className="mt-1 block text-sm text-muted-foreground">{value}</span></>; return <Card className="rounded-2xl text-center"><CardContent className="p-6">{href ? <a href={href}>{content}</a> : content}</CardContent></Card>; }
